              
          
    最近mysql一直down机，日志如下：[wei@zhang data]$ cat zhang.err |tail -n 100InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.InnoDB: Unable to lock ./ibdata1, error: 11InnoDB: Check that you do not already have another mysqld processInnoDB: using the same InnoDB data or log files.130117 19:00:42 InnoDB: Unable to open the first data fileInnoDB: Error in opening ./ibdata1130117 19:00:42 InnoDB: Operating system error number 11 in a file operation.InnoDB: Error number 11 means &#39;Resource temporarily unavailable&#39;.InnoDB: Some operating system error numbers are described atInnoDB: http://dev.mysql.com/doc/refman/5.5/en/operating-system-error-codes.html130117 19:00:42 InnoDB: Could not open or create data files.130117 19:00:42 InnoDB: If you tried to add new data files, and it failed here,130117 19:00:42 InnoDB: you should now edit innodb_data_file_path in my.cnf back130117 19:00:42 InnoDB: to what it was, and remove the new ibdata files InnoDB created130117 19:00:42 InnoDB: in this failed attempt. InnoDB only wrote those files full of130117 19:00:42 InnoDB: zeros, but did not yet use them in any way. But be careful: do not130117 19:00:42 InnoDB: remove old data files which contain your precious data!130117 19:00:42 [ERROR] Plugin &#39;InnoDB&#39; init function returned error.130117 19:00:42 [ERROR] Plugin &#39;InnoDB&#39; registration as a STORAGE ENGINE failed.130117 19:00:42 [ERROR] Unknown/unsupported storage engine: InnoDB130117 19:00:42 [ERROR] Aborting130117 19:00:42 [Note] /usr/local/mysql/bin/mysqld: Shutdown complete130117 19:00:42 mysqld_safe mysqld from pid file /usr/local/mysql/data/zhang.pid ended什么问题呢？排查中！

    ***********************************************************************

    此问题是由于mysql-bin产生的二进制日志文件太大导致，目前mysql-bin日志文件已经接近1G，清理后，mysql正常运行！
    
    
      
来自:http://www.i5good.com/20130117158.html